---
global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "prometheus_service"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: 'rocky_linux_server'
    static_configs:
      - targets: ['192.168.56.102:9100']

  - job_name: 'etsii_alumnos_api'  
    scrape_interval: 10s         
    metrics_path: /metrics        
    static_configs:
      - targets: ['172.17.0.1:3000'] 


